name: horizontalplanning
description: To be able to display an horizontal Planning.
version: 0.0.1
author: Vianney RIOTTE<vianney.riotte@gmail.com
homepage: https://github.com/vianneyriotte/horizontal-planning.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
